### ISSUE TITLE
Premature return in rest_IdealFilter ?

### ISSUE THREAD

**Issue by aweinstein** [BIDS-Apps/rsHRF#12] opened 2021-09-10 18:32 UTC
The `return` statement in the `rest_IdealFilter` function is inside the for loop.

See https://github.com/BIDS-Apps/rsHRF/blob/cf3410664a3a2eda1707f5ee7dc5a7f23fa21492/rsHRF/processing/rest_filter.py#L18

This looks odd to me since that implies that the for loop only executes once, independently of the value of `nbin`.

I must admit that I don't quite understand what the function does, so it is possible that this is OK.

**Comment by NigelCol** [comment] 2021-09-13 08:14
Dear @aweinstein,

Thank you for spotting this error, this was indeed not the intended behaviour. This is a very crucial find, since the function is supposed to band-pass filter the data but now only filtered the first 5000 voxels instead of the whole array as input.
  
It didn't show up in the unit tests, since we tested the function on only a limited amount of data (not exceeding 5000 timeseries).

The fix has been pushed and the function should work as intended now. 

Thanks again!

**Closed by NigelCol** 2021-09-13 08:14 UTC
