### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import (v1.0.1)

### ISSUE THREAD

**Issue by soichih** [BIDS-Apps/rsHRF#2] opened 2019-06-12 10:32 UTC
(I sent an email for this but just for the record let me create this issue here!) 

The Docker container with tag 1.0.1 fails to run with the following error message.

```
[0mModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "/usr/bin/rsHRF", line 6, in <module>
    from rsHRF.CLI import main
  File "/usr/lib/python3.6/site-packages/rsHRF/__init__.py", line 6, in <module>
    import rsHRF.fourD_rsHRF
  File "/usr/lib/python3.6/site-packages/rsHRF/fourD_rsHRF.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/usr/lib/python3.6/site-packages/matplotlib/colorbar.py", line 27, in <module>
    import matplotlib.artist as martist
  File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 13, in <module>
    from .path import Path
  File "/usr/lib/python3.6/site-packages/matplotlib/path.py", line 17, in <module>
    from . import _path, cbook, rcParams
ImportError: numpy.core.multiarray failed to import
```

The new container seems to be using a slightly newer version of python, but apart from that I couldn't really tell why it's failing.

Soichi

**Comment by madhur-tandon** [comment] 2019-06-12 11:07
@soichih This probably looks like an issue with which version of `numpy` is installed. Could you provide me with the data files that you used? That way, I could reproduce the issue and verify it for myself as well.

**Comment by soichih** [comment] 2019-06-27 13:20
@madhur-tandon 

You don't need any input file to reproduce this problem. You can try this.

```
$ singularity exec -e docker://bids/rshrf:1.0.1 python -c "import rsHRF.CLI.main"
Docker image path: index.docker.io/bids/rshrf:1.0.1
Cache folder set to /N/dc2/scratch/hayashis/singularity-cache-carb/docker
Creating container runtime...
Exploding layer: sha256:c87736221ed0bcaa60b8e92a19bec2284899ef89226f2a07968677cf59e637a4.tar.gz
Exploding layer: sha256:de018ce6d111d006b377e721c8a3914fc526812c40c188abed659f92d7d894ae.tar.gz
Exploding layer: sha256:79d44530889bef66f3150df5c230e8c24ca117f15c6782421827b119e4f6c81b.tar.gz
Exploding layer: sha256:aa5481042e4030b6f741357f34df851d6fd5434d77d4947bb15f2951811d4b7f.tar.gz
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/rsHRF/__init__.py", line 6, in <module>
    import rsHRF.fourD_rsHRF
  File "/usr/lib/python3.6/site-packages/rsHRF/fourD_rsHRF.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/usr/lib/python3.6/site-packages/matplotlib/colorbar.py", line 27, in <module>
    import matplotlib.artist as martist
  File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 13, in <module>
    from .path import Path
  File "/usr/lib/python3.6/site-packages/matplotlib/path.py", line 17, in <module>
    from . import _path, cbook, rcParams
ImportError: numpy.core.multiarray failed to import

```

**Comment by markushs** [comment] 2019-08-09 12:50
Hi,

**Comment by madhur-tandon** [comment] 2019-12-20 23:57
@soichih @markushs I have pushed a new build both on DockerHub and on PyPI. The new version is `1.0.8`. I think the error for `numpy.core._multiarray_umath` or `numpy.core.multiarray` is fixed. Could any of you please check and confirm? Let me know, Thanks!

**Comment by soichih** [comment] 2019-12-22 17:35
@madhur-tandon I just tested 1.0.8 container and it finished successfully.

![image](https://user-images.githubusercontent.com/923896/71325214-8a87eb80-24b7-11ea-9757-95991fd24521.png)

![image](https://user-images.githubusercontent.com/923896/71325217-94115380-24b7-11ea-9efe-02d6ea0819a2.png)

**Comment by madhur-tandon** [comment] 2019-12-22 18:06
@soichih Great, I am closing this issue.

**Closed by madhur-tandon** 2019-12-22 18:06 UTC
